config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  root to: 'home#index'

  devise_for(:user, {
    class_name: 'Spree::User',
    singular: :spree_user,
    controllers: {
      sessions: 'user_sessions',
      registrations: 'user_registrations',
      passwords: 'user_passwords',
      confirmations: 'user_confirmations'
    },
    skip: [:unlocks, :omniauth_callbacks],
    path_names: { sign_out: 'logout' }
  })

  resources :users, only: [:edit, :update]

  devise_scope :spree_user do
    get '/login', to: 'user_sessions#new', as: :login
    post '/login', to: 'user_sessions#create', as: :create_new_session
    match '/logout', to: 'user_sessions#destroy', as: :logout, via: Devise.sign_out_via
    get '/signup', to: 'user_registrations#new', as: :signup
    post '/signup', to: 'user_registrations#create', as: :registration
    get '/password/recover', to: 'user_passwords#new', as: :recover_password
    post '/password/recover', to: 'user_passwords#create', as: :reset_password
    get '/password/change', to: 'user_passwords#edit', as: :edit_password
    put '/password/change', to: 'user_passwords#update', as: :update_password
    get '/confirm', to: 'user_confirmations#show', as: :confirmation if Spree::Auth::Config[:confirmable]
  end

  resource :account, controller: 'users'

  resources :products, only: [:index, :show]

  resources :order_contents, only: :create

  get '/locale/set', to: 'locale#set'
  post '/locale/set', to: 'locale#set', as: :select_locale

  # non-restful checkout stuff
  get '/checkout/registration', to: 'checkout#registration', as: :checkout_registration
  put '/checkout/registration', to: 'checkout#update_registration', as: :update_checkout_registration
  patch '/checkout/update/:state', to: 'checkout#update', as: :update_checkout
  get '/checkout/:state', to: 'checkout#edit', as: :checkout_state
  get '/checkout', to: 'checkout#edit', as: :checkout

  get '/orders/:id/token/:token' => 'orders#show', as: :token_order

  resources :orders, except: [:index, :new, :create, :destroy] do
    resources :coupon_codes, only: :create
  end

  get '/cart', to: 'orders#edit', as: :cart
  patch '/cart', to: 'orders#update', as: :update_cart
  put '/cart/empty', to: 'orders#empty', as: :empty_cart

  # route globbing for pretty nested taxon and product paths
  get '/t/*id', to: 'taxons#show', as: :nested_taxons

  get '/unauthorized', to: 'home#unauthorized', as: :unauthorized
  get '/cart_link', to: 'store#cart_link', as: :cart_link

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < StoreController
  before_action :load_product, only: :show
  before_action :load_taxon, only: :index

  helper 'spree/products', 'spree/taxons', 'taxon_filters'

  respond_to :html

  def index
    @searcher = build_searcher(params.merge(include_images: true))
    @products = @searcher.retrieve_products
  end

  def show
    @variants = @product.
      variants_including_master.
      display_includes.
      with_prices(current_pricing_options).
      includes([:option_values, :images])

    @product_properties = @product.product_properties.includes(:property)
    @taxon = Spree::Taxon.find(params[:taxon_id]) if params[:taxon_id]
  end

  private

  def accurate_title
    if @product
      @product.meta_title.blank? ? @product.name : @product.meta_title
    else
      super
    end
  end

  def load_product
    if spree_current_user.try(:has_spree_role?, "admin")
      @products = Spree::Product.with_discarded
    else
      @products = Spree::Product.available
    end
    @product = @products.friendly.find(params[:id])
  end

  def load_taxon
    @taxon = Spree::Taxon.find(params[:taxon]) if params[:taxon].present?
  end
end

app/views/products/_product_availability.html.erb
<%
  base_class = "product-availability".freeze

  # Optional props
  classes = local_assigns.fetch(:classes, [])

  # Classes
  class_names = classes.push(base_class).join(" ")
%>

<% if product.master.can_supply? %>
  <link itemprop="availability" href="http://schema.org/InStock" />
<% elsif product.variants.empty? %>
  <span
    class="<%= class_names %>"
    itemprop="availability"
    href="http://schema.org/OutOfStock"
  >
    <%= t('spree.out_of_stock') %>
  </span>
<% end %>

app/views/products/_product_form.html.erb
<%
  schema_properties = {
    itemprop: 'offers',
    itemscope: true,
    itemtype: 'http://schema.org/Offer'
  }
%>

<%= form_for :order, url: order_contents_path, html: schema_properties do |f| %>
  <% if product_variants_with_options(product).any? %>
    <div class="variant-container">
      <% sorted_option_types(product).each_with_index do |option_type, i| %>
        <div class="variant-selection">
          <%= render 'products/product_selection/option_type', product: product, option_type: option_type, index: i %>
        </div>
      <% end %>
    </div>
  <% end %>

  <%= render 'product_variants', product: product %>

  <% if product.price %>
    <%= render 'product_submit', product: product %>
  <% else %>
    <div id="product-price">
      <p data-js="price" itemprop="price">
        <%= t('spree.product_not_available_in_this_currency') %>
      </p>
    </div>
  <% end %>
<% end %>

app/views/products/_product_header.html.erb
<header class="product-header">
  <h1 class="product-header__title" itemprop="name">
    <%= product.name %>
  </h1>

  <% if product.price_for_options(current_pricing_options)&.money and !product.price.nil? %>
    <h2 class="product-header__title" id="product-price">
      <%= content_tag(
        :span,
        display_price(product),
        itemprop: 'price',
        content: product.price_for_options(current_pricing_options)&.money.to_d,
        data: { js: 'price' }
      ) %>

      <%= content_tag(
        :span,
        nil,
        itemprop: 'priceCurrency',
        content: current_pricing_options.currency
      ) %>
    </h2>
  <% end %>
</header>

app/views/products/_product_image.html.erb
<picture class="product-image">
  <%= render(ImageComponent.new(
    image: product.gallery.images.first,
    size: :product,
    itemprop: "image",
    data: { js: 'product-main-image' }
  )) %>
</picture>

app/views/products/_product_info.html.erb
<div class="product-page__description">
  <h2 class="product-description__title">
    <%= t('description') %>
  </h2>

  <p class="product-description" itemprop="description">
    <%= product_description(product) rescue t('spree.product_has_no_description') %>
  </p>
</div>

app/views/products/_product_promotions.html.erb
<% promotions = product.possible_promotions %>

<% if promotions.any? %>
  <section class="product-promotions">
    <h2><%= t('spree.promotions') %></h2>

    <% promotions.each do |promotion| %>
      <article>
        <header>
          <h3><%= promotion.name %></h3>
        </header>

        <p><%= promotion.description %></p>

        <% if promotion.products.any? %>
          <ul>
            <% promotion.products.each do |product| %>
              <li><%= link_to product.name, product_path(product) %></li>
            <% end %>
          </ul>
        <% end %>
      </article>
    <% end %>
  </section>
<% end %>

app/views/products/_product_properties.html.erb
<% unless product_properties.empty? %>
  <div class="product-page__details">
    <div class="product-properties">
      <h2 class="product-properties__title">
        <%= t('spree.properties')%>
      </h2>

      <table class="product-properties__table">
        <tbody>
          <% product_properties.each do |product_property| %>
            <tr>
              <td><%= product_property.property.presentation %></td>
              <td><%= product_property.value %></td>
            </tr>
          <% end %>

          <% reset_cycle('properties') %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

app/views/products/_product_submit.html.erb
<div class="product-submit">
  <%= render 'product_availability', product: product %>

  <div class="horizontal-input-group">
    <div class="horizontal-input-group__input">
      <div class="text-input">
        <%= text_field_tag :quantity, 1, type: :number, min: 1 %>
      </div>
    </div>
    <div class="horizontal-input-group__action">
      <%= button_tag(
        t('spree.add_to_cart'),
        class: 'button-primary',
        id: 'add-to-cart-button'
      ) %>
    </div>
  </div>
</div>

app/views/products/_product_thumbnails.html.erb
<ul class="product-thumbnails">
  <% product.gallery.images.each do |image| %>
    <% next if image.viewable_id != product.master.id %>

    <%= content_tag(
      :li,
      class: 'product-thumbnails__all',
      data: { js: 'product-thumbnail', js_id: image.viewable_id }
    ) do %>
      <%= link_to(image_tag(image.url(:mini)), image.url(:product)) %>
    <% end %>
  <% end %>

  <% if product.has_variants? %>
    <% product.gallery.images.each do |image| %>
      <% next if image.viewable_id == product.master.id %>

      <%= content_tag(
        :li,
        class: 'product-thumbnails__variant',
        data: { js: 'variant-thumbnail', js_id: image.viewable_id }
      ) do %>
        <%= link_to(image_tag(image.url(:mini)), image.url(:product)) %>
      <% end %>
    <% end %>
  <% end %>
</ul>

app/views/products/_products-grid.html.erb
<%
  base_class = "products-grid".freeze

  # Optional props
  classes = local_assigns.fetch(:classes, [])

  # Classes
  class_names = classes.push(base_class).join(" ")
%>

<ul class="<%= class_names %>">
  <% products.each do |product| %>
    <%= render 'products/product-card', product: product %>
  <% end %>
</ul>

app/views/products/_products.html.erb
<%
  paginated_products = @searcher.retrieve_products if params.key?(:keywords)
  paginated_products ||= products
  no_products_found = products.empty?
%>

<% content_for :head do %>
  <% if paginated_products.respond_to?(:total_pages) %>
    <%= rel_next_prev_link_tags paginated_products %>
  <% end %>
<% end %>

<% if no_products_found %>
  <h2 class="products__results-title">
    <%= t('spree.no_products_found') %>
  </h2>
<% elsif params.key?(:keywords) %>
  <h1 class="products__results-title">
    <%= t('spree.search_results', keywords: h(params[:keywords])) %>
  </h1>
<% end %>

<% if !no_products_found %>
  <%= render 'products/products-grid', products: products %>
<% end %>

<% if paginated_products.respond_to?(:total_pages) %>
  <%= paginate paginated_products %>
<% end %>

app/views/products/_products_by_taxon.html.erb
<section class="products-by-taxon">
  <h5 class="products-by-taxon__title">
    <%= link_to products_by_taxon.name, taxon_seo_url(products_by_taxon) %>
  </h5>

  <%= render 'products/products', products: taxon_preview(products_by_taxon), taxon: products_by_taxon %>
</section>

app/views/products/index.html.erb
<div class="products">
  <aside>
    <% if "products" == params[:controller] && @taxon %>
      <%= render 'shared/search/filters', taxon: @taxon %>
    <% else %>
      <%= render 'shared/navigation/taxonomies', taxon: @taxon %>
    <% end %>
  </aside>
  <section class="products_section">
    <% if params[:keywords] %>
      <% if @products.empty? %>
        <h6>
          <%= t('spree.no_products_found') %>
        </h6>
      <% else %>
        <%= render 'products', products: @products, taxon: @taxon %>
      <% end %>
    <% else %>
      <%= render 'products', products: @products, taxon: @taxon %>
    <% end %>
  </section>
</div>

app/views/products/show.html.erb
<% @body_id = 'product-details' %>

<% cache [I18n.locale, current_pricing_options, @product] do %>
  <article class="product-page" itemscope itemtype="http://schema.org/Product">
    <div class="product-page-row">
      <div class="product-page__images">
        <%= render 'product_image', product: @product %>
        <%= render 'product_thumbnails', product: @product %>
      </div>

      <div class="product-page__info">
        <%= render 'product_header', product: @product %>
        <%= render 'product_promotions', product: @product %>
        <%= render 'product_form', product: @product %>
        <%= render 'product_taxons', product: @product %>
      </div>
    </div>

    <div class="product-page-row">
      <%= render 'product_info', product: @product %>
      <%= render 'product_properties', product_properties: @product_properties %>
    </div>
  </article>
<% end %>